---
title: "airparif"
author: "Sarah Hosking"
date: "Oct 10 2017"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(GGally)

library(reshape2) #plot missing vals

theme_set(theme_bw())

```

## Read files


```{r air pollution in paris Aug 2017}

airparif <- read.csv("airparif_centre_13_8_2017.csv", sep = ";", stringsAsFactors = FALSE)

#airparif <- read.csv("airparif_centre_8_12_2016.csv", sep = ";", stringsAsFactors = FALSE)

#airparif <- read.csv("airparif_centre_8_12_2016.csv", sep = ";")

dim(airparif)
str(airparif)
summary(airparif)
head(airparif,20)
tail(airparif,20)

```

```{r convert col types}

airparif[,3:7] <- lapply(airparif[,3:7], as.numeric)
str(airparif)

```

```{r}

head(airparif)
```

There seems to be a LOT of NA values

```{r}
# credit to:
# http://www.njtierney.com/r/missing%20data/rbloggers/2015/12/01/ggplot-missing-data/
missing.data <- function(x){

  x %>%
    is.na %>%
    melt %>%
    ggplot(data = .,
           aes(x = Var2,
               y = Var1)) +
    geom_raster(aes(fill = value)) +
    scale_fill_grey(name = "",
                    labels = c("Present","Missing")) +
    theme_minimal() +
    theme(axis.text.x  = element_text(angle=45, vjust=0.5)) +
    labs(x = "Variables in Dataset",
         y = "Rows / observations")
}

missing.data(airparif[,1:7])
```


## Prepare the data

Where is the NA date?

```{r}

which(is.na(airparif$date))

# look at vals before & after this row
airparif[211:214,]

# okay this happened on '29/07/2011' @ 20h
# TODO: replace with locf (from dplyr?)
airparif$date[213] <- '29/07/2011'
airparif[211:214,]

```


Let's convert the date var into a true Date type variable

```{r convert str date into date}

airparif$date <- as.Date(airparif$date, format = "%d/%m/%Y")
str(airparif)

```

Then we can use tidyR's `separate` function to split these into day, month and year variables.

```{r split date into y m d vars}

# remove 1st row
airparif <- airparif[-1,]
str(airparif)

```

```{r add y m d}

# make a copy
 airparif$date2 <- airparif$date
#
 airparif <- separate(airparif, date2, c("year", "month", "day"), sep="-")
# str(airparif)

#  Convert year month day to ordered factor
 airparif[,8:10] <- lapply(airparif[,8:10], factor, ordered = TRUE)

# str(airparif)

```

```{r save as rds}

write_rds(airparif, "airparif_oct2017.rds")

```


